application: hd-domain
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /_km/.*
  script: shared/lib/keymaster.py
  login: admin
- url: /auth/.*
  script: auth.py
- url: .*
  script: main.py

builtins:
- deferred: on

